### ISSUE TITLE
Stuck in pip install -r requirements/edx/github.txt

### ISSUE THREAD

**Issue by FranckMARIN** [regisb/openedx-install#17] opened 2017-12-07 13:06 UTC
Hi,
First of all thanks for your documentation on OpenEDX installation. Everything is pretty clear.

However, I'm stuck on the step "pip install -r requirements/edx/github.txt". I have this error :
AttributeError: 'module' object has no attribute 'lru_cache'

My OS is Ubuntu 16.04.3 LTS and I can't figure how to deal with this error without break anything else by using python3.

Thanks in advance for your help.

**Comment by regisb** [comment] 2017-12-07 13:21
Hmmmm... Do you know which package is causing the error? Please include the full error stacktrace.

Don't switch to Python 3! Open edX is compatible with Python 2.7 *only*.

**Comment by franckm06** [comment] 2017-12-07 14:40
The package causing the error seems to be django2.

```
Collecting futures>=2.1.3 (from django-pipeline==1.5.3->-r requirements/edx/github.txt (line 49))
  Using cached futures-3.2.0-py2-none-any.whl
Collecting Django>=1.4 (from django-wiki==0.0.9->-r requirements/edx/github.txt (line 50))
  Using cached Django-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QPfEHf/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
```

**Comment by regisb** [comment] 2017-12-07 14:52
Wait, are you using python 3 ? What does `python --version` say?

**Comment by regisb** [comment] 2017-12-07 15:01
Hmmmm looks like django-wiki is depending on `Django>=1.4`. Apparently, Django is not already installed, so pip pulls the best match, which is `Django==2.0`, which is not supported in Open edX. Actually, Django 2.0 does not support Python 2.7 at all: https://docs.djangoproject.com/en/2.0/releases/2.0/#python-compatibility

So, what we should do is install an appropriate version of Django *before* running `pip install -r requirements/edx/github.txt`. Try running: 

    pip install Django==1.8.18

And then:

    pip install -r requirements/edx/github.txt

I'll update the documentation once I found a better fix.

**Comment by FranckMARIN** [comment] 2017-12-07 16:03
Thank you very much, my OpenEDX is UP and Running.

**Comment by regisb** [comment] 2017-12-07 16:06
\o/ I'll leave this issue open to remind me of fixing the documentation.

**Comment by regisb** [comment] 2018-01-20 14:10
I suspect the issue is that requirements from 'github.txt' were installed before 'pre.txt', so there is nothing to do in Ginkgo. Closing this. Thanks @FranckMARIN for raising this issue!

**Closed by regisb** 2018-01-20 14:10 UTC
